### PR TITLE
Roles Modal Enhancements

### PR DESCRIPTION
**Pull request by reeved**
# Description
Adds Jester information to the Roles and Rules Modal. Also implemented proper functionality to let players know what their roles are.

# Demo
Before: 
image

After: 
image

# Type of change:
* New feature (Non-breaking change that adds functionality)
* Bug fix (Non-breaking change which fixes a bug)

# Checklist:
* Have you merged main into your branch?
* Have you tested your changes to ensure it works as expected and does not break existing functionality?
* If applicable, please ensure sufficient tests are added that is related to the changes.
* Please ensure this PR has a `label`, is linked to an `issue` and is related to a `project`
* If new documentation is required for this change, have you created a new documentation issue that describes the documentation needed?

### CODE REVIEW

**Comment by reeved** [comment]
Sorry, just noticed a bug when trying to open the rules on the lobby screen. Please wait till a fix has been submitted before reviewing :D

**Review by skyn310198 — APPROVED** [review]
LGTM !!! good work

**Review by ateagit — APPROVED** [review]
LGTM

**Review by jteo97 — APPROVED** [review]
Good quality of life changes. Well done

**Pull request merged**
