### PR TITLE
#182 enhancement/changed winner message

### PR DESCRIPTION
**Pull request by atha670**
# Description
This PR fixes #[182]

Please include a summary of the changes here.
Just changed the final text that is displayed in the game over text. 

# Demo
(Please include screenshots/GIF here if applicable)

After: 
image

# Type of change:
(Delete the ones that are not relevant)
* Bugfix (Non-breaking change which fixes a bug)

# Checklist:
* Have you merged main into your branch?
* Have you tested your changes to ensure it works as expected and does not break existing functionality?
* If applicable, please ensure sufficient tests are added that is related to the changes.
* Please ensure this PR has a `label`, is linked to an `issue` and is related to a `project`
* If new documentation is required for this change, have you created a new documentation issue that describes the documentation needed?

### CODE REVIEW

**Comment by atha670** [comment]
@reeved  I tried deleting my version of the last file and it wouldn't let me.

**Comment by Dhors** [comment]
Please use the tags and labels properly

**Review by reeved — CHANGES_REQUESTED** [review]
Hi Arjun,

Could you instead use a status message for this? Personally feel like putting it in the TopBar isn't appropriate because it should be used more for displaying short information like screen name or the timer. 
The statusbar on the other hand is used to display long messages like inside the game. 

There isn't a game over status currently generated in the gameState so you would need to add one, then grab it for use in the gameOverScreen. 

Conditionally outputting the 's' instead of having (s) in Winners would be cool too, but not as important :)

Remember to grab the latest changes from upstream before working on this and don't delete any files

**Comment by atha670** [comment]
Had to redo this branch due to merge conflicts not be resolved efficiently. After considering the reviewer's comments, I had a look at the code and there was a case for the 'game over' state in one of the game state files.

**Pull request closed without merging**
