### PR TITLE
Updated roles and rules css so that it doesn't look strange on smaller monitors

### LINKED ISSUE #341: Fix frontend roles and rules looking squished
**Describe the bug**
See screenshot.

**To Reproduce**
1. Create a new game.
2. Look up rules.

**Expected behavior**
All the cards should be separated out as designed in the wiki.

**Screenshots**
image

### Issue Approval:
- [x]  Issue approved by: @khal745

### PR DESCRIPTION
**Pull request by milkyway404**
Closes #341 

Before: 
image

After: 
image
image

# Type of change:
* Bug fix (Non-breaking change which fixes a bug)

### CODE REVIEW

**Comment by AngelaLH** [comment]
Looks great on my screen now as well :D Just a quick fix - the "your role" sticker does not scroll (this is for civilian & then mafia)
image
image

**Review by hsingh124 — APPROVED** [review]
Tested on my local machine with different screen sizes, looks good to me! Great work!

**Review by JChamberlain28 — APPROVED** [review]
Tested on my computer. Works well. Thanks for this fix.

**Review by yzho976 — COMMENTED** [review]
Really nice work. Thanks for fixing it!

**Pull request merged**
