### PR TITLE
Feature/chat

### LINKED ISSUE #260: Add a player text chat to pre-game lobby
### In-Depth Feature Description:
- Right now it is assumed that players will be in zoom/discord calls when playing, but text chat would be valuable to add to the experience. 
- This issue is specifically for implementing text chat in the pre-game lobby

### Blocked by issues:

- [ ] #

### Sub-Task List:

- [ ] Allow all roles to text each other during pre-game lobby

### Additional context: 
- A dummy chat has been implemented in the frontend
- A socket.io example for a chat implementation can be found here: 
https://github.com/socketio/socket.io-website/blob/master/source/get-started/chat.md

### Issue Approval:

- [x] Issue approved by:
@hsingh124

### PR DESCRIPTION
**Pull request by hsingh124**
# Description
This PR fixes #260

Please include a summary of the changes here.
Add a text chat to the pre game lobby screen. All current players in the lobby can see messages in real time. New players are unable to see the history of the chat.

# Demo

To test it on the local server, in the file **frontend/src/Socket.js**:
comment line 5 `const socket = new socketIOClient('mafia-hands-backend-cd.herokuapp.com');` 
uncomment line 8 `const socket = new socketIOClient('localhost:4001');`

## Before:
Screen Shot 2021-04-06 at 1 37 52 PM

## After:
Screen Shot 2021-04-06 at 1 36 28 PM

# Type of change:
(Delete the ones that are not relevant)
* New feature (Non-breaking change that adds functionality)

# Checklist:
* Have you merged main into your branch?
* Have you tested your changes to ensure it works as expected and does not break existing functionality?
* If applicable, please ensure sufficient tests are added that is related to the changes.
* Please ensure this PR has a `label`, is linked to an `issue` and is related to a `project`
* If new documentation is required for this change, have you created a new documentation issue that describes the documentation needed?

### CODE REVIEW

**Review by flexzy — DISMISSED** [review]
Worked together and pair programmed most of this with @hsingh124. I've tested on my own computer and all functionality works as expected. The chat is responsive and all players can see new messages quickly. LGTM!

**Review by a-158w — DISMISSED** [review]
Initially worked on this with @hsingh124 and @flexzy. The finished code looks good - I like the way state has been handled by elevating it to a parent component. Good work!

**Review by milkyway404 — DISMISSED** [review]
Thank you for the amazing work guys!! It's awesome to see a chat function for this app. Only thing I'm concerned about is the changes to the `package.json` and `package-lock.json` --were these necessary? They're too big for me to review :( but I was able to look at the frontend `package.json` where it doesn't seem as though anything has changed. Would you be able to revert that change? 

I've tested on my local machine and I have to say, the chat function is amazing!! Thanks for clarifying on Discord about why it wasn't working locally. To add a note: Currently the app uses the backend hosted on a server, but the backend changes aren't deployed to that server until this PR is merged in to the main branch.

**Review by flexzy — DISMISSED** [review]
LGTM! don't know why my other approval isn't marked as approve anymore :(

**Review by flexzy — APPROVED** [review]
Great job rebasing and getting this functionality working brilliantly Harpreet! I've tested on my own computer and all functionality still works as expected. The code also seems to be robust since I haven't found any bugs! LGTM!

**Review by a-158w — APPROVED** [review]
This looks good to me. Code runs and the functionality works well. I approve of the way state is being used and how the chat functionality is set up under the hood. Good work!

**Pull request merged**
