### PR TITLE
Closes #267: Removed logic from backend that caused jester to be considered mafia for detective votes

### LINKED ISSUE #267: Jester revealed as mafia for the detective
**Describe the bug**
Currently, if the detective queries the jester, it reveals them as mafia. This was initially done as an intentional implementation to ensure that the jester is not revealed as a member of the town. 

However, this can be misleading for the detective as they might think the jester is the mafia. 

**To Reproduce**
1. Start the game with 6 instances of the app
2. Go to the tab with the detective role
3. Query the player with the jester role

**Expected behavior**
The jester should either be revealed as not-mafia or not part of the town

**Additional context**
This was initially done as an intentional implementation to ensure that the jester is not revealed as a member of the town.

**Desktop (please complete the following information):**
 - OS: Windows + Mac
 - Browser: Chrome

### Issue Approval:
- [x]  Issue approved by: JChamberlain28

### PR DESCRIPTION
**Pull request by JChamberlain28**
# Description
This PR fixes #267

Removed logic in the `/backend/Events/NightTimeVoteEvents.js` logic to not consider jesters as mafia when responding to a vote request from a detective during the night.

Before: 
image
image

After:
image
image

# Type of change:
* Bug fix (Non-breaking change which fixes a bug)

### CODE REVIEW

**Review by ambiyu — DISMISSED** [review]
LGTM

**Review by kyzh0 — DISMISSED** [review]
LGTM

**Review by ODE-BOY — DISMISSED** [review]
LGTM

**Comment by JChamberlain28** [comment]
Note: a test that checked the detective voting functionality was failing. This has been changed to pass only if the player voted for is mafia and they are revealed as mafia. This removes the part of the test that checks that jesters are revealed as mafia, as this is no longer the intended functionality.

**Review by khal745 — APPROVED** [review]
LGTM - thanks for fixing up the old test! Maybe we need to consider updating documentation but I don't believe anything states that Jesters should be revealed as Mafia as it was previously.

**Comment by JChamberlain28** [comment]
> LGTM - thanks for fixing up the old test! Maybe we need to consider updating documentation but I don't believe anything states that Jesters should be revealed as Mafia as it was previously.

I checked this and nothing states this.

**Review by ambiyu — APPROVED** [review]
LGTM. Thanks for fixing this issue.
In the game rules documentation, it says "Detective will choose someone to check if the player is a Mafia or not". I think it is clear that detectives can only check Mafias already.

**Pull request merged**
