### PR TITLE
Move linting configs to package dependency to fix build issues

### LINKED ISSUE #125: Global ESlint Config File / Refactor
**Is your feature request related to a problem? Please describe.**
Currently, the ESLint config files are stored separately for backend and frontend. This prevents the pre-commit hook from running both the lint tests and instead, only runs one. Also, to enforce consistency in the entire project, it would be better to have one global config file. 

**Describe the solution you'd like**
Global config file in the root directory which stores the rules for both frontend and backend. 

**Describe alternatives you've considered**
Separate config files for frontend and backend (current structure)

**Additional context**

### Checklist:
- [ ] Frontend
- [ ] Backend

### Feature Approval:
- [x]  Feature approved by: @parfei

### PR DESCRIPTION
**Pull request by LindaBot**
# Description
This PR fixes #125

`npm run start` calls `react-scripts start` which invokes linting. All of the eslint configs and plugins are stored as a devDependency so it wouldn't get installed on the server at buildtime/runtime. Solution is to move the configs to the dependency so they get installed. 

I've also remove eslint configs that we are not using. 

# Type of change:
* Bug fix (Non-breaking change which fixes a bug)

# Demo:
*  Before: https://mafia-hands-frontend-cd.herokuapp.com/ (As of 11:17 PM 24/03/2021)

* After: https://mafia-david-test.herokuapp.com/

# Checklist ✅
* Have you merged main into your branch?
* Have you tested your changes to ensure it works as expected and does not break existing functionality?
* If applicable, please ensure sufficient tests are added that is related to the changes.
* Please ensure this PR has a `label`, is linked to an `issue` and is related to a `project`
* If new documentation is required for this change, have you created a new documentation issue that describes the documentation needed?

### CODE REVIEW

**Review by jteo97 — APPROVED** [review]
Looks good

**Review by reeved — APPROVED** [review]
LGTM. Thanks David :)

**Review by jge385 — APPROVED** [review]
LGTM!

**Review by ateagit — APPROVED** [review]
lgtm

**Pull request merged**
