### PR TITLE
Closes #269: Early timer termination for day, trial, and night stages of the game

### LINKED ISSUE #269: Terminate the timer and vote when everyone has voted
**Is your feature request related to a problem? Please describe.**
I have to wait for the timer to elapse despite everyone having voted. 

**Describe the solution you'd like**
Terminate the timer once everyone has cast their vote. 

**Describe alternatives you've considered**
Let the timer running in case people wish to change their vote

### Feature Approval:
- [ ]  Feature approved by:

### PR DESCRIPTION
**Pull request by flexzy**
# Description
This PR fixes #269 

During all there stages of the game (day, trial and night), the votes are counted and the game moves onto the next stage of the game when all possible votes have been cast, instead of having to wait for the timer to complete.

# Demo
Unable to depict these changes through screenshots.
Just make sure that when testing, change the file **frontend/src/Socket.js** to use the local server.

# Type of change:
* New feature (Non-breaking change that adds functionality)

# Checklist:
* Have you merged main into your branch?
* Have you tested your changes to ensure it works as expected and does not break existing functionality?
* If applicable, please ensure sufficient tests are added that is related to the changes.
* Please ensure this PR has a `label`, is linked to an `issue` and is related to a `project`
* If new documentation is required for this change, have you created a new documentation issue that describes the documentation needed?

### CODE REVIEW

**Review by cng822 — DISMISSED** [review]
Thanks for doing this Felix! Code looks amazing and neat. Glad that we no longer need wait for everyone to finished in order to move to the next stage of the game. I noticed that the checks are all good now too. LGTM 👍

**Review by werer9 — DISMISSED** [review]
Lgtm Felix. Really nicely written and glad that it finally works

**Review by cng822 — DISMISSED** [review]
Good job on spotting the bug. Will approve!

**Review by hsingh124 — DISMISSED** [review]
Looks good to me. The functionality is working really well! Good work!!

**Comment by flexzy** [comment]
I have reverted and pushed the package-lock to what it was before feature/chat was merged into a2-main. This is because that pull request introduced the chokidar error in frontend for some Windows machines.

**Review by cng822 — APPROVED** [review]
The following changes will definitely be helpful for window users. I would definitely this in mind if I was to ever push a package-lock. Appreciate the changes!

**Review by hsingh124 — APPROVED** [review]
Tested on my windows machine. Looks pretty good. No errors. Thanks for the package-lock fix @flexzy!

**Pull request merged**
