### PR TITLE
#184 Add screen change transition

### LINKED ISSUE #184: Add Screen Change Transitions
**What are the tasks that need to be done?**
- [ ] Transitions between Game Flow Screen Changes e.g. from Night to Discussion Period

### In-Depth Feature Description
At the moment, screen changes are quite sudden and can be quite jarring. Some sort of transition/animation would help make the game feel "smoother"

### Images for Reference:
None, sorry!

### Feature Approval:
- [ ]  Feature approved by:

### PR DESCRIPTION
**Pull request by jge385**
# Description
This PR fixes #184

Add fade in animation for the entry screen, game over screen, and status bar
Add zoom effect to the hoverable circle in the table

# Type of change:
* New feature (Non-breaking change that adds functionality)

# Checklist:
* Have you merged main into your branch?
* Have you tested your changes to ensure it works as expected and does not break existing functionality?
* If applicable, please ensure sufficient tests are added that is related to the changes.
* Please ensure this PR has a `label`, is linked to an `issue` and is related to a `project`
* If new documentation is required for this change, have you created a new documentation issue that describes the documentation needed?

### CODE REVIEW

**Review by SreenikethRaghavan — APPROVED** [review]
LGTM

**Comment by SreenikethRaghavan** [comment]
Can the PR info such as milestone, tags, projects etc. please be filled out @jge385

**Comment by zxia545** [comment]
The fade-in animation may have some bug that sometimes does not work.

**Review by zxia545 — APPROVED** [review]
Look good to me! The problem of fade-in is solved.

**Pull request merged**
