### PR TITLE
Add host player to room in MafiaGameMock

### LINKED ISSUE #275: MafiaGameMock creates a hostPlayer but it is actually not assigned to the room created
**Please describe the bug**
`MafiaGameMock` creates a hostPlayer but does not assign to the room that is created -- it was only created so that it can avoid `socket.player.roomID` bugs in the test.

Current unit tests assume this hostPlayer is not in the `room.players` array anyway - we create all players of the room manually. However, it is confusing that we create a hostplayer but it is not assigned to the `room.players` array, and when we first mock MafiaGame, the function called is `createMafiaGameWithOnePlayerMock`. In the actual unit tests, we never use this hostPlayer created, and it is not being used when calculating the votes in the tests, for example in `DayStateChangeEvents.unit.test.js`

For instance:
image
In this unit test, we have added two players. But there should actually be a third - the hostPlayer that we have first created. In reality, there are only two players in the `room.players` array, so when we are calculating votes, we only regard the two players constructed above.

**Describe the solution you'd like**
Add the hostplayer in `MafiaGameMock` to the `room.players` array -- i.e. `room.addPlayer(hostPlayer)`
Adjust all unit tests so that it takes into account this new player (i.e. `NightStateChangeEvents.unit.test.js` units create its room players manually; now it will have this extra hostPlayer to take into account, and similar)

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

### Bug Approval:
- [ ]  Bug approved by:

### PR DESCRIPTION
**Pull request by kyzh0**
# Description
This PR fixes #275 

Add the hostplayer in `MafiaGameMock` to the `room.players` array and modify the tests so they behave as expected and pass.

# Demo
N/A

# Type of change:
* Bug fix (Non-breaking change which fixes a bug)

### CODE REVIEW

**Review by ODE-BOY — DISMISSED** [review]
Looks Good, All Tests pass and the additions are quite comprehensive. Good Job.

**Review by maheknangia — DISMISSED** [review]
Looks good to me! Thanks for this

**Review by ODE-BOY — APPROVED** [review]
Looks Good, All Tests pass and the additions are quite comprehensive. Good Job

**Review by maheknangia — APPROVED** [review]
Looks good to me! Thanks for this

**Pull request merged**
