### PR TITLE
Home screen combine

### LINKED ISSUE #88: Link the HomeScreen component
**What are the tasks that need to be done?**
- [Design HomeScreen with Material UI ]
- [Create another HomeScreen alternative when someone join with /{id}]
- [Link with other screen that is already available]

### In-Depth Feature Description
-Create the HomeScreen for the user to enter their nickname, lobby id or create game. Link this with other available screen.

### Images for Reference:
image

### PR DESCRIPTION
**Pull request by skyn310198**
# Description
This PR fixes #88
Create 2 version of HomeScreen component for when user enter the game with/without /{id}

# Demo
Before: 
image

After: 
image
image

# Type of change:
* New feature (Non-breaking change that adds functionality)

### CODE REVIEW

**Review by zxia545 — APPROVED** [review]
Good work!

**Comment by reeved** [comment]
Hi, 

Just some issues from my end before I am willing to approve this PR:

1. It would be great to see more Material UI components being used. Going forward, all input items should use Material UI components. Checkout: [MUI Text Fields](https://material-ui.com/components/text-fields/), [MUI Buttons](https://material-ui.com/components/buttons/#button) and their respective APIs that you can view at the bottom of each page.

2. Please use the TopBarSettings component instead of creating your own Header bar for consistency in this app. I'll modify the component to also conditionally render the back button so that you don't need to show it in this screen.

**Comment by skyn310198** [comment]
> Hi,
> 
> Just some issues from my end before I am willing to approve this PR:
> 
> 1. It would be great to see more Material UI components being used. Going forward, all input items should use Material UI components. Checkout: [MUI Text Fields](https://material-ui.com/components/text-fields/), [MUI Buttons](https://material-ui.com/components/buttons/#button) and their respective APIs that you can view at the bottom of each page.
> 2. Please use the TopBarSettings component instead of creating your own Header bar for consistency in this app. I'll modify the component to also conditionally render the back button so that you don't need to show it in this screen.

Noted, i will modify the existed components to Material UI, and will change the top bar to TopBarSettings to keep the consistency in this app. Cheers

**Comment by skyn310198** [comment]
After changing to Material UI:
Enter game without /{id}
image

Enter game with /{id}
image

**Pull request merged**
