### PR TITLE
Restructure unit tests for backend

### LINKED ISSUE #164: Restructure backend unit testing
### In-Depth Feature Description:

The backend unit tests are quire monolithic at the moment, so they need to be restructured to make it easier to add more tests. This involves:
- Creating more files/test suites to separate different test cases
- Set up more robust mock objects that can be used to test late-game functionalities

### Images for Reference:

N/A
### Blocked by issues:
N/A

### Sub-Task List:

- [ ] Mock objects for game starts and adding players.
- [ ] Separation of tests to different suites, where similar test cases are grouped together.
- [ ] Adding unit tests for voting events.

### Issue Approval:

- [x] Issue approved by: @MKTPR

### LINKED ISSUE #177: ListVoteDTO only requires a nickname in its voteMap value
### In-Depth Feature Description:
The frontend team does not need a `Player` object in the `ListVoteDTO`'s `voteMap` values. We should change it so that it returns nicknames for both key and values in the map pairs.

### Issue Approval:

- [x] Issue approved by: @MKTPR

### PR DESCRIPTION
**Pull request by seif-y**
# Description
This PR fixes #164 and fixes #177

Minor changes have been added to the MafiaGameMock component, to make it usable for more unit tests. It can now be used for lobby admin and voting events. Also added the ability to switch the player attached to the testing client socket, so that tests are able to simulate actions from multiple different players.

Also moved all the tests into different files, and organised different test suites inside each file, to group similar tests together. (The tests from the old `index.test.js` have been moved to `unit/LobbyAdmin.test.js` and `unit/VotingEvents.test.js`)

# Demo
N/A

# Type of change:
(Delete the ones that are not relevant)
* New feature (Non-breaking change that adds functionality)

### CODE REVIEW

**Comment by seif-y** [comment]
Right now the voting event tests are failing because the changes for issue #177 have not been implemented yet. For some reason this is causing issues with Jest not exiting after the tests have completed.

**Comment by seif-y** [comment]
> Right now the voting event tests are failing because the changes for issue #177 have not been implemented yet. For some reason this is causing issues with Jest not exiting after the tests have completed.

Update: this PR now handles issue #177 as well.

**Review by UltimaKuma — APPROVED** [review]
LGTM

**Review by absternator — APPROVED** [review]
Looks good to me. Great job

**Pull request merged**
