### PR TITLE
Fix pretty quick command missing issue

### LINKED ISSUE #89: Pretty quick command is missing
The pretty quick package is missing from the package.json file therefore I am creating this issue for submitting a pull request to fix this up.

### PR DESCRIPTION
**Pull request by SiyuQian**
# Description
This PR fixes #89 
Adding the pretty quick package back to the package.json file as a devDependencies.

### CODE REVIEW

**Comment by SiyuQian** [comment]
Hey guys, looks like the commit is not clean somehow that some commits from the other team members are included in pull request too for some reason. 
Does anyone know what is happening here?

**Comment by reeved** [comment]
You might have had an older version of upstream synced to your local repo. 

Probably best to close this PR, resync from upstream then submit a new PR since you're just adding a dependency.

**Comment by SiyuQian** [comment]
> You might have had an older version of upstream synced to your local repo.
> 
> Probably best to close this PR, resync from upstream then submit a new PR since you're just adding a dependency.

Nope. I pulled upstream man.

**Comment by reeved** [comment]
> > You might have had an older version of upstream synced to your local repo.
> > Probably best to close this PR, resync from upstream then submit a new PR since you're just adding a dependency.
> 
> Nope. I pulled upstream man.

Weird. I'd still just try pulling again. Not sure what has happened. Let us know if it happens again on fresh pull from upstream.

**Comment by SiyuQian** [comment]
nvm. I will fix this then close this one and reopen one.

**Pull request closed without merging**
