### PR TITLE
Add return to lobby button to the GameOverPage

### LINKED ISSUE #167: Add reset lobby functionality
**What are the tasks that need to be done?**
- [x] Respond to reset lobby event. 
- [x] Reset the game state.
- [x] Have a return to lobby button

### In-Depth Feature Description
There is functionality in the backend to reset a lobby after the game is finished. Unfortunately, this hasn't been implemented in the front end. A button should be provided (or a timeout) to send people back to lobby. 

### Feature Approval:
- [x]  Feature approved by: @MKTPR

### PR DESCRIPTION
**Pull request by SiyuQian**
# Description
This PR resolves #167 

* Trigger event
* Delete returnToLobbyButton component and move to GameOverPage

# Demo
Screen Shot 2021-03-21 at 3 08 43 AM

# Type of change:
* New feature (Non-breaking change that adds functionality)

# Checklist:
* Have you merged main into your branch?
* Have you tested your changes to ensure it works as expected and does not break existing functionality?
* If applicable, please ensure sufficient tests are added that is related to the changes.
* Please ensure this PR has a `label`, is linked to an `issue` and is related to a `project`
* If new documentation is required for this change, have you created a new documentation issue that describes the documentation needed?

### CODE REVIEW

**Comment by SiyuQian** [comment]
@ateagit Alan, Looks like the code is not working properly (not changing the state and the reducer did not trigger) for some reason. Could you please give me some suggestions?  Not really familiar with this code structure.

**Comment by ateagit** [comment]
> @ateagit Alan, Looks like the code is not working properly (not changing the state and the reducer did not trigger) for some reason. Could you please give me some suggestions? Not really familiar with this code structure.

Mostly everythings working
In `useLobbyState` the event that is sent back to players after a reset-lobby request is called `reset-lobby-update` so change
```
socket.on('reset-lobby', onResetLobby); to socket.on('reset-lobby-update', onResetLobby);
```
and since I think we want to go back to lobby, just change to lobby screen instead of home so in `onResetLobby()`

```
dispatch({ type: 'change-screen', screen: 'home' }); to  dispatch({ type: 'change-screen', screen: 'lobby' });
```

**Review by ateagit — APPROVED** [review]
LGTM

**Comment by reeved** [comment]
Closed as #232 finishes off this PR.

**Pull request closed without merging**
