### PR TITLE
Feature/show detective suspect role

### PR DESCRIPTION
**Pull request by tguernier**
# Description
This PR fixes part of #180

This PR adds text indicating whether a player that the detective has suspected is a Mafia or not, using the contents of gameState.checkedPlayers.

# Demo
(Please include screenshots/GIF here if applicable)

After: 

(the Mafia/not Mafia text only shows for the Detective)

# Type of change:
(Delete the ones that are not relevant)
* New feature (Non-breaking change that adds functionality)

# Checklist:
* Have you merged main into your branch?
* Have you tested your changes to ensure it works as expected and does not break existing functionality?
* If applicable, please ensure sufficient tests are added that is related to the changes.
* Please ensure this PR has a `label`, is linked to an `issue` and is related to a `project`
* If new documentation is required for this change, have you created a new documentation issue that describes the documentation needed?

### CODE REVIEW

**Review by Dhors — APPROVED** [review]
I feel there may be issues if the detective selects multiple users at once
Edit: Just tested, and it turns out detective can select and see roles of all players in the first night.

I'm not too sure of a way around this for now.

**Comment by tguernier** [comment]
Issue: Can reveal all players' roles by clicking all of them in one turn

**Review by Dhors — CHANGES_REQUESTED** [review]
image
1 turn you can send them all,
Since we are sending in packets, i feel it would be best to give the suspect message at the end, with the player was killed during night messages, that way the player to suspect is only set at end of night.

**Review by Dhors — CHANGES_REQUESTED** [review]
image
1 turn you can send them all,
Since we are sending in packets, i feel it would be best to give the suspect message at the end, with the player was killed during night messages, that way the player to suspect is only set at end of night.

**Review by Dhors — DISMISSED** [review]
image

If detective afks the first night, then they can click 2 people in the second night, while this is not game breaking since detective can't use more role reveals than the night count, I feel this is broken logic and should be reconsidered.

Could we consider alans solution of trying to prevent detective from being able to send a second event for role reveal in the same night?

**Comment by tguernier** [comment]
Used @ateagit's solution of checking gameState.votingState.vote - now should only allow one other player to be checked per night regardless of day number

**Review by atha670 — APPROVED** [review]
Good to merge it

**Review by ateagit — APPROVED** [review]
LGTM

**Pull request merged**
