### PR TITLE
Closes #273: Changed case to lower case for backend folders/packages

### LINKED ISSUE #273: Change all backend package names to use a lowercase convention
### In-Depth Feature Description:
Currently some backend packages start with uppercase alphabets. Change package names to be all lowercase. 

### Issue Approval:

- [x] Issue approved by: JChamberlain28

### PR DESCRIPTION
**Pull request by JChamberlain28**
# Description
This PR fixes #273

To achieve a lower case only package structure, skewer case was used in place of camel case
- renamed `/backend/Events` to `backend/events`
- renamed `/backend/Events/GameStateEvents` to `/backend/events/game-state-events`
- renamed `/backend/domain/DTO` to `/backend/domain/dto`
- renamed `/backend/domain/Enum` to `/backend/domain/enum`

# Type of change:
* Bug fix (Non-breaking change which fixes a bug)

### CODE REVIEW

**Comment by JChamberlain28** [comment]
I have found some folders that are still upper case. Updating the PR

**Comment by JChamberlain28** [comment]
updated PR

**Review by khal745 — CHANGES_REQUESTED** [review]
I think you need to update some files and the tests to use the new paths with `require()` calls eg. `VotingEvents.unit.test.js` is failing because of the line ` const VoteForDTO = require('../../domain/DTO/request/VoteForDTO');` using the old `DTO` folder name

**Comment by JChamberlain28** [comment]
> I think you need to update some files and the tests to use the new paths with `require()` calls eg. `VotingEvents.unit.test.js` is failing because of the line ` const VoteForDTO = require('../../domain/DTO/request/VoteForDTO');` using the old `DTO` folder name

Will get onto this. I forgot to ctrl F for instances of that folder.

**Review by milkyway404 — CHANGES_REQUESTED** [review]
Thanks for the changes Jack! Looking at the tests it seems that some folder name/imports weren't updated causing test failures. Could you please change those? I know they're easy to miss, so you can use `npm run test` to ensure that everything is changed :)

**Comment by JChamberlain28** [comment]
Note this PR may break and cause conflicts due to the introduction of new references to the pre-renamed folders in the main repo. These should be fixed when the PR is ready to merge. Merging has been held off until the current PR's are merged as not to cause conflict with all of them. This means only one PR will have conflict, rather than all the others.

**Comment by JChamberlain28** [comment]
major issues with the merge so having to start again

**Pull request closed without merging**
